code_guide_ids = [
                            "A00-B99, U07.1, U09.9",
                            "C00-D49",
                            "D50-D89",
                            "E00-E89",
                            "F01-F99",
                            "G00-G99",
                            "H00-H59",
                            "H60-H95",
                            "I00-I99",
                            "J00-J99, U07.0",
                            "K00-K95",
                            "L00-L99",
                            "M00-M99",
                            "N00-N99",
                            "O00-O9A",
                            "P00-P96",
                            "Q00-Q99",
                            "R00-R99",
                            "S00-T88",
                            "V00-Y99",
                            "Z00-Z99",
                            "U00-U85",
                        ]

code_guide_meta = [
                            {
                                "entity": "chapter",
                                "index": 1,
                                "id": "A00-B99, U07.1, U09.9",
                                "description": "Certain Infectious and Parasitic Diseases (A00-B99), U07.1, U09.9",
                            },
                            {
                                "entity": "chapter",
                                "index": 2,
                                "id": "C00-D49",
                                "description": "Neoplasms (C00-D49)",
                            },
                            {
                                "entity": "chapter",
                                "index": 3,
                                "id": "D50-D89",
                                "description": "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism (D50-D89)",
                            },
                            {
                                "entity": "chapter",
                                "index": 4,
                                "id": "E00-E89",
                                "description": "Endocrine, Nutritional, and Metabolic Diseases (E00-E89)",
                            },
                            {
                                "entity": "chapter",
                                "index": 5,
                                "id": "F01-F99",
                                "description": "Mental, Behavioral and Neurodevelopmental Disorders (F01-F99)",
                            },
                            {
                                "entity": "chapter",
                                "index": 6,
                                "id": "G00-G99",
                                "description": "Diseases of the Nervous System (G00-G99)",
                            },
                            {
                                "entity": "chapter",
                                "index": 7,
                                "id": "H00-H59",
                                "description": "Diseases of the Eye and Adnexa (H00-H59)",
                            },
                            {
                                "entity": "chapter",
                                "index": 8,
                                "id": "H60-H95",
                                "description": "Diseases of the Ear and Mastoid Process (H60-H95)",
                            },
                            {
                                "entity": "chapter",
                                "index": 9,
                                "id": "I00-I99",
                                "description": "Diseases of the Circulatory System (I00-I99)",
                            },
                            {
                                "entity": "chapter",
                                "index": 10,
                                "id": "J00-J99, U07.0",
                                "description": "Diseases of the Respiratory System (J00-J99), U07.0",
                            },
                            {
                                "entity": "chapter",
                                "index": 11,
                                "id": "K00-K95",
                                "description": "Diseases of the Digestive System (K00-K95)",
                            },
                            {
                                "entity": "chapter",
                                "index": 12,
                                "id": "L00-L99",
                                "description": "Diseases of the Skin and Subcutaneous Tissue (L00-L99)",
                            },
                            {
                                "entity": "chapter",
                                "index": 13,
                                "id": "M00-M99",
                                "description": "Diseases of the Musculoskeletal System and Connective Tissue (M00-M99)",
                            },
                            {
                                "entity": "chapter",
                                "index": 14,
                                "id": "N00-N99",
                                "description": "Diseases of the Genitourinary System (N00-N99)",
                            },
                            {
                                "entity": "chapter",
                                "index": 15,
                                "id": "O00-O9A",
                                "description": "Pregnancy, Childbirth, and the Puerperium (O00-O9A)",
                            },
                            {
                                "entity": "chapter",
                                "index": 16,
                                "id": "P00-P96",
                                "description": "Certain Conditions Originating in the Perinatal Period (P00-P96)",
                            },
                            {
                                "entity": "chapter",
                                "index": 17,
                                "id": "Q00-Q99",
                                "description": "Congenital malformations, deformations, and chromosomal abnormalities (Q00-Q99)",
                            },
                            {
                                "entity": "chapter",
                                "index": 18,
                                "id": "R00-R99",
                                "description": "Symptoms, signs, and abnormal clinical and laboratory findings, not elsewhere classified (R00-R99)",
                            },
                            {
                                "entity": "chapter",
                                "index": 19,
                                "id": "S00-T88",
                                "description": "Injury, poisoning, and certain other consequences of external causes (S00-T88)",
                            },
                            {
                                "entity": "chapter",
                                "index": 20,
                                "id": "V00-Y99",
                                "description": "External Causes of Morbidity (V00-Y99)",
                            },
                            {
                                "entity": "chapter",
                                "index": 21,
                                "id": "Z00-Z99",
                                "description": "Factors influencing health status and contact with health services (Z00-Z99)",
                            },
                            {
                                "entity": "chapter",
                                "index": 22,
                                "id": "U00-U85",
                                "description": "Codes for Special Purposes (U00-U85)",
                            },
                        ]